server:
  port: 80
  tomcat:
    max-swallow-size: 100MB
  address: 105.52.55.57

spring:
  profiles:
    active: test
  main:
    allow-circular-references: true
  datasource:
    mysql:
      driver-class-name: ${ecom.datasource.mysql.driver-class-name}
      jdbcUrl: jdbc:mysql://${ecom.datasource.mysql.host}:${ecom.datasource.mysql.port}/${ecom.datasource.mysql.database}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&allowLoadLocalInfile=true
      username: ${ecom.datasource.mysql.username}
      password: ${ecom.datasource.mysql.password}
    vertica:
      driver-class-name: ${ecom.datasource.vertica.driver-class-name}
      #url: jdbc:mysql://${ecom.datasource.host}:${ecom.datasource.port}/${ecom.datasource.database}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&allowLoadLocalInfile=true
      jdbcUrl: ${ecom.datasource.vertica.url}
      username: ${ecom.datasource.vertica.username}
      password: ${ecom.datasource.vertica.password}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB







mybatis:
  #mapper????
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ecom.pojo.entity
  configuration:
    #??????
    map-underscore-to-camel-case: true

logging:
  level:
    Root: debug
#    com:
#      ecom:
#        mapper: debug
#        service: info
#        controller: debug

ecom:
  jwt:
    # ??jwt??????????
    admin-secret-key: itcast
    # ??jwt????
    admin-ttl: 7200000
    # ?????????????
    admin-token-name: token
    user-secret-key: qinlang
    user-token-name: authentication
    user-ttl: 7200000

  local-upload-folder:
    path: ${ecom.local-upload-folder.path}

