ecom:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.vertica.jdbc.Driver
    url: 'jdbc:vertica://usdd-vertica.seacda.com:5431/verticadb'
    username: l.qin3
    password: l#e8nIzxa0S

  local-upload-folder:
    path: "C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Data\\ecomtoolbox"

  redis:
    host: localhost
    port: 6379
    password: 12345


