ecom:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    vertica:
      driver-class-name: com.vertica.jdbc.Driver
      url: ''
      username:
      password:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      host: localhost
      port: 3306
      database: ecomtoolbox
      username: root
      password:

  local-upload-folder:
    path: ""

  redis:
    host: localhost
    port: 6379
    password:


