ecom:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.vertica
    host: localhost
    port: 3306
    database: ecomtoolbox
    username: root
    password: 12345

  local-upload-folder:
    path: "C:\\Users\\l.qin3\\Documents\\uploads"

  redis:
    host: localhost
    port: 6379
    password: 12345


