ecom:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: ecom
    username: root
    password: 12345

  local-upload-folder:
    path: "C:\\Users\\qinla\\Documents\\SpringBootDelivery\\day01\\upload"

  redis:
    host: localhost
    port: 6379
    password: 12345


